/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('./components/Back.vue')['default']
    Developer: typeof import('./components/Developer.vue')['default']
    FlipImage: typeof import('./components/FlipImage.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Giscus: typeof import('./components/Giscus.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    ListPhotos: typeof import('./components/ListPhotos.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    ListProjects: typeof import('./components/ListProjects.vue')['default']
    ListTags: typeof import('./components/ListTags.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Nutshell: typeof import('./components/Nutshell.vue')['default']
    Project: typeof import('./components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComp: typeof import('./components/SearchComp.vue')['default']
    TextCopy: typeof import('./components/TextCopy.vue')['default']
    WrapperPhoto: typeof import('./components/WrapperPhoto.vue')['default']
  }
}
